image: node:buster

stages:
  - test

lint:
  stage: test
  before_script:
    - yarn
  script:
    - yarn lint
  rules:
    - if: $CI_COMMIT_BRANCH != "master"

test:
  stage: test
  before_script:
    - yarn
  script:
    - yarn test:coverage
  rules:
    - if: $CI_COMMIT_BRANCH != "master"
  coverage: /All files\s*\|\s*([\d\.]+)/

mutation-test:
  stage: test
  before_script:
    - yarn
  script:
    - yarn test:mutations
  rules:
    - when: manual
