name: Conventional Changelog

on:
  [push]
  # push:
  # tags:
  #   - 'v*'

jobs:
  conventional-changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Conventional Changelog Action
        uses: TriPSs/conventional-changelog-action@v3.14.0
        with:
          github-token: ${{ secrets.github_token }}
          git-message: 'chore(release): {version}'
          tag-prefix: 'v'
          git-branch: 'develop'
          # skip-commit: 'true'

  create-release:
    uses: conventional-changelog
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        uses: actions/create-release@v1
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          release_name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}
